name: '🐛 Bug Report'
description: "If something isn't working as expected."
title: '[Bug]: '
body:
  - type: checkboxes
    id: input1
    attributes:
      label: '💻'
      options:
        - label: Would you like to work on a fix?

  - type: textarea
    attributes:
      label: Current and expected behavior
      description: A clear and concise description of what the app is doing and what you would expect.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Possible solution
      description: 'If you have suggestions on a fix for the bug.'

  - type: textarea
    attributes:
      label: Additional context
      description: 'Add any other context about the problem here. Or a screenshot if applicable.'
